### ISSUE TITLE
genomes.find_linear: TypeError from bisect

### ISSUE THREAD

**Issue by borshago** [grexor/pybio#3]
Hi,

The genomes function find_linear throws the following error:

> .../genomes/__init__.py", line 475, in find_linear
    index = bisect.bisect_left(genome_linear, (pos,"",""))
TypeError: '<' not supported between instances of 'int' and 'str'

A workaround that worked for me is to use tuples of two integers:

```
genome_linear_coords = [i[0:2] for i in genome_linear] 
index = bisect.bisect_left(genome_linear_coords, (pos,pos))
```

Best,
Daniel

**Comment by grexor** [comment]
Your solution should also work, however in Python 3* I also have no problems with the current code, could you debug further and provide an example? (which genome / position does the error happen with?)

Thanks, Gregor

**Comment by borshago** [comment]
Hi,

I'm using python 3.7.6 and genome hg38/ensembl97. This error pops up when running apa.comps with these samples:

https://expressrna.org/share/data/20150203_ina/e1/20150203_ina_e1.fastq.bz2
https://expressrna.org/share/data/20150203_ina/e1/20150203_ina_e2.fastq.bz2
https://expressrna.org/share/data/20150203_ina/e1/20150203_ina_e3.fastq.bz2
https://expressrna.org/share/data/20150203_ina/e1/20150203_ina_e4.fastq.bz2

I added the first line of the following to the original genomes/__init__.py script:

```
print(pos)
index = bisect.bisect_left(genome_linear, (pos, "", ""))
```

The apa.comps run produces the following output:

> 200589312
> 217608194
> 226631690
> 32333839
> 149848082
> 224227349
> 58654745
> 229593120
> 67014691
> 42176548
> 54169659
> 67412028
> 24154173
> 84643915
> 77942866
> 114704470
> 54849634
> 84664435
> 38862964
> 235253881
> 169463931
> 83865724
> 110653567
> 220057728
> 165724292
> Traceback (most recent call last):
>    File "bin/apa.comps", line 11, in <module>
>        apa.comps.process_comps(args.comps_id, map_id=args.map_id)
>    File "/scratch/project_2001351/Daniel/CONDA/ENVS/apa_py3/lib/python3.7/site-packages/apa/comps/__init__.py", line 396, in process_comps
>        (gene_up, gene_id, gene_down, gene_interval, gene_feature) = pybio.genomes.annotate(comps.species, chr, strand, pos)
>    File "/scratch/project_2001351/Daniel/CONDA/ENVS/apa_py3/lib/python3.7/site-packages/pybio/genomes/__init__.py", line 422, in annotate
>        closest_index, gene_id = find_linear(genome_linear, pos) # if gene_id==None, pos is intergenic, closest_index is upstream linear
>   File "/scratch/project_2001351/Daniel/CONDA/ENVS/apa_py3/lib/python3.7/site-packages/pybio/genomes/__init__.py", line 476, in find_linear
>     index = bisect.bisect_left(genome_linear, (pos, "", ""))
> TypeError: '<' not supported between instances of 'int' and 'str'

Incidentally, position 165724292 is the start for the locus of gene ENSG00000143183 (TMCO1). In the elib.pairs_de.tab file I got by running the modified script (1st post), the line for this gene is missing both "proximal_pas" and "distal_pas" values. Line 2218 (including the header) in the file: https://drive.google.com/open?id=1oOpcXTH7qusRiv4ZySzyKgxs7MaYnXAF.

Have you tested the apa workflow with python 3.7.*?


Best,
Daniel
