### ISSUE TITLE
prepare or prepare_gtf to be used?

### ISSUE THREAD

**Issue by aparajitadutta** [grexor/pybio#4]
Hi Gregor,

I have been using your tool to develop a simplified version of the tool for my requirement of figuring out differentially expressed polyA sites. Taking aid of your recent documentation, I have been able to generate the polyA atlas. Currently I am figuring out the call annotation(poly_id) in the process function of apa/polya directory. 

What I understand is:

annotate(poly_id) calls pybio.genomes.annotate,
pybio.genomes.annotate calls load(species) which requires the genes, intervals and linear json.

genes, intervals and linear json are created in prepare and prepare_gtf.
Please let me know if I am going the right way? If yes, which function should I use: prepare or prepare_gtf?

**Comment by grexor** [comment]
Hello aparajitadutta,

Yes, this is part of pybio, and is part of "loading" (preparing) the genomes from ensembl. Can you check the scripts in the pybio/genomes folder? Things should work out of the box from there?

Cheers,
Gregor

**Comment by aparajitadutta** [comment]
Hi Gregor,

Yes this helps. I see "prepare" function being called in those scripts. I am being curious about the use of prepare_gtf.

Do not see that being used... Is it not required or any particular scenario when prepare_gtf will be required?

Regards,
Aparajita

**Comment by grexor** [comment]
The `prepare_gtf` is used on GTF files of genomes, however for Ensembl we download a TAB file over biomart with all the annotation info and prefer to use that file (processed by `prepare`).
